import:
  - ~/.config/alacritty/ayu-mirage.yml

env:
  TERM: xterm-256color

window:
  position:
    x: 1920
    y: 1080
  opacity: 1.00
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 10.0
  normal:
    family: Iosevka SS08
    style: Medium
  bold:
    family: Iosevka SS08
    style: Bold
  italic:
    family: Iosevka SS08
    style: Italic
  bold_italic:
    family: Iosevka SS08
    style: Bold Italic
      
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

live_config_reload: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"     

mouse:
  hide_when_typing: true

key_bindings:
  - { key: K,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineUp      }
  - { key: J,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineDown    }
  - { key: PageUp,    mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: PageDown,  mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: U,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: D,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: Home,      mods: Control|Shift,   mode: ~Alt,        action: ScrollToTop,      }
  - { key: End,       mods: Control|Shift,   mode: ~Alt,        action: ScrollToBottom    }
  - { key: Return,    mods: Control|Shift,                      action: SpawnNewInstance  }
  - { key: Key0,      mods: Control,                            action: ResetFontSize     }
  - { key: Equals,    mods: Control,                            action: IncreaseFontSize  }
  - { key: Minus,     mods: Control,                            action: DecreaseFontSize  }
  - { key: F,         mods: Control|Shift,   mode: ~Search,     action: SearchForward     }
