# import:
#   - ~/.config/alacritty/catppuccin.yml

env:
  TERM: xterm-256color

window:
  position:
    x: 1920
    y: 1080
  opacity: 0.97
  dynamic_title: true
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 10.0
  normal:
    family: Iosevka Nerd Font
    style: Medium
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic
      
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

live_config_reload: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"     

mouse:
  hide_when_typing: true

# Colors (Nord)
# Source: https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml

colors:
  primary:
    background: '#2e3440'      # nord0; darkest in Polar Night
    foreground: '#d8dee9'      # nord4; darkest in Snow Storm
    dim_foreground: '#a5abb6'  # intermediate gray
  cursor:
    text: '#000000'    # nord0; darkest in Polar Night
    cursor: '#81A1C1'  # nord4; darkest in Snow Storm
  vi_mode_cursor:
    text: '#2e3440'    # nord0; darkest in Polar Night
    cursor: '#d8dee9'  # nord0; darkest in Polar Night
  selection:
    text: CellForeground
    background: '#4c566a'   # nord3; lightest in Polar Night
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'    # nord1; one shade lighter than nord0
    red: '#bf616a'      # nord11
    green: '#a3be8c'    # nord14
    yellow: '#ebcb8b'   # nord13
    cyan: '#88c0d0'     # nord8; 2nd-lightest in Frost
    blue: '#81a1c1'     # nord9; 2nd-darkest in Frost
    magenta: '#b48ead'  # nord15
    white: '#e5e9f0'    # nord5; intermediate in Snow Storm
  bright:
    black: '#4c566a'    # nord3; lightest in Polar Night
    red: '#bf616a'      # nord11
    green: '#a3be8c'    # nord14
    yellow: '#ebcb8b'   # nord13
    cyan: '#8fbcbb'     # nord7; lightest in Frost
    blue: '#81a1c1'     # nord9; 2nd-darkest in Frost
    magenta: '#b48ead'  # nord15
    white: '#eceff4'    # nord6; lightest in Snow Storm
  dim:
    black: '#373e4d'    # dark black-blue-gray
    red: '#94545d'      # muted version of nord11
    green: '#809575'    # muted version of nord14
    yellow: '#b29e75'   # muted version of nord13
    blue: '#68809a'     # muted version of nord10
    magenta: '#8c738c'  # muted version of nord15
    cyan: '#6d96a5'     # muted version of nord7
    white: '#aeb3bb'    # darkened version of nord4
    
key_bindings:
  - { key: K,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineUp      }
  - { key: J,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineDown    }
  - { key: PageUp,    mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: PageDown,  mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: U,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: D,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: Home,      mods: Control|Shift,   mode: ~Alt,        action: ScrollToTop,      }
  - { key: End,       mods: Control|Shift,   mode: ~Alt,        action: ScrollToBottom    }
  - { key: Return,    mods: Control|Shift,                      action: SpawnNewInstance  }
  - { key: Key0,      mods: Control,                            action: ResetFontSize     }
  - { key: Equals,    mods: Control,                            action: IncreaseFontSize  }
  - { key: Minus,     mods: Control,                            action: DecreaseFontSize  }
  - { key: F,         mods: Control|Shift,   mode: ~Search,     action: SearchForward     }
