import:
  - ~/.config/alacritty/ayu-mirage.yml

window:
  opacity: 1.00

font:
  size: 10.0
  normal:
    family: Iosevka Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic
      
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Live config reload (changes require restart)
live_config_reload: true

key_bindings:
  - { key: K,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineUp      }
  - { key: J,         mods: Control|Shift,   mode: ~Alt,        action: ScrollLineDown    }
  - { key: PageUp,    mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: PageDown,  mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: U,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageUp, }
  - { key: D,         mods: Control|Shift,   mode: ~Alt,        action: ScrollHalfPageDown}
  - { key: Home,      mods: Control|Shift,   mode: ~Alt,        action: ScrollToTop,      }
  - { key: End,       mods: Control|Shift,   mode: ~Alt,        action: ScrollToBottom    }
  - { key: Return,    mods: Control|Shift,                      action: SpawnNewInstance  }
  - { key: Key0,      mods: Control,                            action: ResetFontSize     }
  - { key: Equals,    mods: Control,                            action: IncreaseFontSize  }
  - { key: Minus,     mods: Control,                            action: DecreaseFontSize  }
  - { key: F,         mods: Control|Shift,   mode: ~Search,     action: SearchForward     }
