# Brewfile for macOS dotfiles setup

# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# CLI Tools
brew "git"
brew "vim"
brew "neovim"
brew "tmux"
brew "zsh"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "bat"
brew "exa"
brew "tree"
brew "wget"
brew "curl"

# Development Tools
brew "node"
brew "python"
brew "rustup-init"

# Fonts
cask "font-fira-code"
cask "font-hack-nerd-font"

# Applications
cask "iterm2"
cask "visual-studio-code"
cask "firefox"