#background  #263238
foreground  #eceff1

cursor                #d0d0d0

selection_foreground  #2e3440
selection_background  #eceff4

# Black
color0                #263238
# Bright black
color8                #37474f

# red
color1                #ff9800
# light red
color9                #ffa74d

# green
color2                #8bc34a
# light green
color10               #9ccc65

# yellow
color3                #ffc107
# light yellow
color11               #ffa000

# blue
color4                #03a9f4
# light blue
color12               #81d4fa

# magenta
color5                #e91e63
# light magenta
color13               #ad1457

# cyan
color6                #009688
# lighy cyan
color14               #26a69a

# light gray
color7                #cfd8dc
# dark gray
color15               #eceff1
