foreground  #d8dee9
background  #2d3743

cursor                #d0d0d0

selection_foreground  #2e3440
selection_background  #eceff4

# Black
color0                #3b4252
# Bright black
color8                #4c566a

# red
color1                #bf616a
# light red
color9                #bf616a

# green
color2                #a3be8c
# light green
color10               #a3be8c

# yellow
color3                #ebcb8b
# light yellow
color11               #ebcb8b

# blue
color4                #81a1c1
# light blue
color12               #81a1c1

# magenta
color5                #b48ead
# light magenta
color13               #b48ead

# cyan
color6                #88c0d0
# lighy cyan
color14               #8fbcbb

# light gray
color7                #e5e9f0
# dark gray
color15               #eceff4
