"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "nord"
continuation_prompt = "[❯❯ ](nord3)"

[fill]
symbol = ' '

[directory]
format = "[$path]($style)"
style = "bold nord9"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = "  "
style = "nord3"
format = "[$symbol$branch]($style)"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](nord15)($ahead_behind$stashed)]($style)"
style = "nord8"
modified = "*"
untracked = "?"
staged = "+"
conflicted = "="
ahead = "⇡"
behind = "⇣"

[character]
success_symbol = "[❯](nord14)"
error_symbol = "[❯](nord11)"
vimcmd_symbol = "[❮](nord9)"

[cmd_duration]
format = "[$duration]($style)"
style = "nord13"

[python]
detect_extensions = []
detect_files = []
detect_folders = []
format = ' [py:$virtualenv]($style)'
style = "nord3"

# https://www.nordtheme.com/docs/colors-and-palettes
[palettes.nord]
nord0 = "#2E3440"
nord1 = "#3B4252"
nord2 = "#434C5E"
nord3 = "#4C566A"
nord4 = "#D8DEE9"
nord5 = "#E5E9F0"
nord6 = "#ECEFF4"
nord7 = "#8FBCBB"
nord8 = "#88C0D0"
nord9 = "#81A1C1"
nord10 = "#5E81AC"
nord11 = "#BF616A"
nord12 = "#D08770"
nord13 = "#EBCB8B"
nord14 = "#A3BE8C"
nord15 = "#B48EAD"
