" Basic configuration settings
" --------------------------------------------

syntax enable
set nocompatible
filetype plugin on
filetype indent on
filetype on
set encoding=utf-8
set wrap linebreak
set number relativenumber
set cursorline
set ruler
set showcmd

colorscheme nord
