#!/usr/bin/env bash

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.config/X11/xprofile ] && . ~/.config/X11/xprofile
[[ -f ~/.config/X11/Xresources ]] && xrdb -merge -I$HOME ~/.config/X11/Xresources

exec i3
