#!/usr/bin/env bash

picom -b --config ~/.config/picom/picom.conf &
env GTK_THEME=Arc-Dark nm-applet --no-agent &
setxkbmap br &
dunst &
xss-lock -l -- i3lock -c 000000 &
xset r rate 300 50 &
nitrogen --restore &
redshift -l -7.15:-34.84 -t 5700:3600 -g 0.8 -m randr &
