format = "$directory$git_branch$character"
add_newline = false

[character]
success_symbol = "[\\$](#f4f4f4)"
error_symbol = "[\\$](#bf616a)"
vicmd_symbol = "[\\$](#13c3f6)"

[directory]
truncation_length = 10
format = "[$path$read_only ](#a586f5)"
truncate_to_repo = false

[git_branch]
format = "[\\($branch(:$remote_branch)\\)](bold green) "

[cmd_duration]
disabled = true

[lua]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "R "

[conda]
ignore_base = false
