#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output
import os
import re

config = dict(os.environ)
status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "<span color='red'><span font='FontAwesome'>\uf00d \uf240</span></span>"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is
    # available for each battery separately, although state and remaining
    # time for overall block is shown in the status of the first battery
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    time = ""
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            if not time:
                time = commasplitstatus[-1].strip()
                # check if it matches a time
                time = re.match(r"(\d+):(\d+)", time)
                if time:
                    time = ":".join(time.groups())
                    timeleft = " ({})".format(time)
                else:
                    timeleft = ""

            p = int(commasplitstatus[1].rstrip("%\n"))
            if p>0:
                percentleft_batteries.append(p)
            commasplitstatus_batteries.append(commasplitstatus)
    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    if percentleft_batteries:
        percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))
    else:
        percentleft = 0

    # stands for using battery\uf240
    FA_BATTERY = "<span font='FontAwesome'>{}</span>"

    # stands for unknown status of battery
    FA_QUESTION = "<span font='FontAwesome'>\uf128</span>"

    if state == "Discharging":
        if percentleft < 10:
            stateself = " "
        elif percentleft < 20:
            stateself = " "
        elif percentleft < 30:
            stateself = " "
        elif percentleft < 40:
            stateself = " "
        elif percentleft < 50:
            stateself = " "
        elif percentleft < 60:
            stateself = " "
        elif percentleft < 70:
            stateself = " "
        elif percentleft < 80:
            stateself = " "
        elif percentleft < 90:
            stateself = " "
        else:
            stateself = " "
    elif state == "Charging":
        if percentleft < 10:
            stateself = " "
        elif percentleft < 30:
            stateself = " "
        elif percentleft < 45:
            stateself = " "
        elif percentleft < 65:
            stateself = " "
        elif percentleft < 80:
            stateself = " "
        elif percentleft < 95:
            stateself = " "
        else:
            stateself = " "
    elif state == "Full":
        stateself = " "
        timeleft = ""
    elif state == "Unknown":
        stateself = ""
        timeleft = ""
    else:
        stateself = None

    def color(percent):
        if percent < 10:
            # exit code 33 will turn background red
            return "#000000"
        if percent < 20:
            return "#FF3300"
        if percent < 30:
            return "#FF6600"
        if percent < 40:
            return "#FF9900"
        if percent < 50:
            return "#FFCC00"
        if percent < 60:
            return "#FFFF00"
        if percent < 70:
            return "#FFFF77"
        if percent < 80:
            return "#FFFFaa"
        return "#8FBCBB"

    form =  '<span color="{}">{}{}%</span>'
    fulltext = form.format(color(percentleft), stateself, percentleft)
    fulltext += timeleft

print(fulltext)

if percentleft < 10:
    exit(33)
