# Set the default terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:RGB"

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# vim mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
set-option -g focus-events on
set -g mouse on
set -g cursor-style default
set -sg escape-time 0
set -g history-limit 50000

set -g xterm-keys on

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on     # renumber windows when a window is closed
set -g set-titles on           # set terminal title
set -g set-titles-string '#T'  # set terminal title to window name

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes

bind-key r source-file ~/.config/tmux/tmux.conf

# Switch panes using Alt-arrow without prefix
bind -n 'M-h' select-pane -L
bind -n 'M-j' select-pane -D
bind -n 'M-k' select-pane -U
bind -n 'M-l' select-pane -R

# Switch windows using 1/2 
bind -n 'M-,' previous-window 
bind -n 'M-.' next-window 

# Open new panes/windows
bind-key 'h' split-window -h
bind-key 'v' split-window -v

# Toggle status bar
bind -n 'M-m' set-option -g status

# Open new panes/windows in current path
bind H split-window -h -c '#{pane_current_path}'
bind V split-window -v -c '#{pane_current_path}'
bind C new-window -c '#{pane_current_path}'

# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#{?client_prefix,#[fg=#2E3440]#[bg=#D08770 bold]  #S ,#[fg=${green_soft}]#[bg=default]  #S }#[bg=default]#[fg=${gray_light},nobold]|"
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g status-right "#{?#{m:*ssh*,#{pane_current_command}},#[fg=#BF616A]#[bg=default]  SSH ,}#[fg=#D8DEE9]#[bg=default] %H:%M · %d/%m "
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/tpm/tpm'
