# Set the default terminal
set -g default-terminal "xterm-ghostty"
set -ag terminal-overrides ",xterm-256color:RGB"
# set-option -g default-shell /opt/homebrew/bin/fish

source-file ~/.config/tmux/nordic.tmuxtheme

# rebind prefix to C-a
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# vim mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
set-option -g focus-events on
set -g mouse on
set -sg escape-time 10
set -g history-limit 5000

set -g xterm-keys on

setw -g automatic-rename off   # rename window to reflect current program
set -g renumber-windows on     # renumber windows when a window is closed
set -g set-titles on           # set terminal title
set -g set-titles-string '#W'  # set terminal title to window name

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

bind-key r source-file ~/.config/tmux/tmux.conf

# Switch panes using Alt-arrow without prefix
bind -n 'M-h' select-pane -L
bind -n 'M-j' select-pane -D
bind -n 'M-k' select-pane -U
bind -n 'M-l' select-pane -R

# Switch windows using 1/2 
bind -n 'M-,' previous-window 
bind -n 'M-.' next-window 

# split
bind-key 'v' split-window -h
bind-key 'g' split-window -v

# Toggle status bar
bind -n 'M-m' set-option -g status

# Open new panes/windows in current path
bind H split-window -h -c '#{pane_current_path}'
bind V split-window -v -c '#{pane_current_path}'
bind C new-window -c '#{pane_current_path}'
