#!/usr/bin/env bash

[[ -d ${HOME}/bin ]] && export PATH=$PATH:${HOME}/bin
[[ -d ${HOME}/.local/bin ]] && export PATH=$PATH:${HOME}/.local/bin
[[ -d ${HOME}/.local/xmgrace/bin ]] && export PATH=$PATH:${HOME}/.local/xmgrace/bin
[[ -f ${HOME}/.config/X11/Xresources ]] && xrdb -merge -I${HOME} ${HOME}/.config/X11/Xresources

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

xrandr --output eDP1 --primary --mode "1920x1080"

picom -b --log-file $HOME/.local/share/picom/picom.log --config ${HOME}/.config/picom/picom.conf --vsync &
xset r rate 300 50 &
xset +dpms s 60 180 &
xss-lock -n ${HOME}/.local/bin/dim-screen.sh -- ${HOME}/.local/bin/my_i3lock &
redshift -l -7.15:-34.84 -t 6500:4500 -g 0.8 -m randr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst -conf ${HOME}/.config/dunst/dunstrc &

while :; do
	exec qtile start
done
